services:
    php-fpm:
        build:
            args:
                user: webuser
                uid: 1000
            context: ./docker
            dockerfile: Dockerfile.fpm
        container_name: "${APP_NAME}_php_fpm"
        tty: true
        restart: unless-stopped
        logging:
            options:
                max-size: "5k"
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ./docker/php-fpm/laravel.ini:/usr/local/etc/php/conf.d/app.ini
        networks:
            - default
        expose:
            - "9000"
        depends_on:
            - mysql

    nginx:
        build:
            context: "./docker/nginx"
            args:
                queueTimeout: 30
                queueTries: 2
                queues: default,indexing,notifications
        container_name: "${APP_NAME}_nginx"
        restart: unless-stopped
        depends_on:
            - php-fpm
        environment:
            PUSHER_PORT: ${PUSHER_PORT}
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            - ./docker/localhost/:/etc/letsencrypt/live/localhost/
            - ./docker/certbot:/var/www/html/public/.well-known/:rw
            - /etc/letsencrypt/:/etc/letsencrypt/:rw
        ports:
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_HTTP_PORT}:80"
        networks:
            - default

    mysql:
        container_name: "${APP_NAME}_MYSQL"
        image: mysql:8.0  # Suporta ARM64
        tty: true
        command: --default-authentication-plugin=mysql_native_password --max_connections=666 --bind-address=0.0.0.0 --transaction-isolation=READ-COMMITTED
        restart: unless-stopped
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TIMEZONE: "America/Sao_Paulo"
        volumes:
            - rl-mysql:/var/lib/mysql
            - "./create-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
        networks:
            - default

    phpmyadmin:
        container_name: "${APP_NAME}_PHPMYADMIN"
        image: phpmyadmin/phpmyadmin:latest  # Suporta ARM64
        restart: unless-stopped
        ports:
            - 8082:80
        environment:
            PMA_HOSTS: mysql
            PMA_PORT: ${FORWARD_DB_PORT:-3306}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 350M
        depends_on:
            - mysql
        networks:
            - default

    redis:
        image: "redis:alpine"
        container_name: "${APP_NAME}_redis"
        restart: unless-stopped
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "${DATA_PATH_HOST}/redis:/data"
        networks:
            - default
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

volumes:
    downloads:
        driver: local
    rl-mysql:
        driver: local
    sail-redis:
        driver: local

networks:
    default:
        driver: bridge
